<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Vitriol.Shared\Vitriol.Shared.csproj" />
    <ProjectReference Include="..\Vitriol.Data\Vitriol.Data.csproj" />
    <ProjectReference Include="..\Vitriol.Engine\Vitriol.Engine.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
